language: objective-c
sudo: false
osx_image: xcode7.3
os:
- linux
go:
- 1.6.4
- 1.7.4
- 1.8.1
- tip
install:
- git fetch --unshallow --tags
- make vars
- make build_dep
script:
- make check
- make quicktest
env:
  matrix:
    secure: gU8gCV9R8Kv/Gn0SmCP37edpfIbPoSvsub48GK7qxJdTU628H0KOMiZW/T0gtV5d67XJZ4eKnhJYlxwwxgSgfejO32Rh5GlYEKT/FuVoH0BD72dM1GDFLSrUiUYOdoHvf/BKIFA3dJFT4lk2ASy4Zh7SEoXHG6goBlqUpYx8hVA=
matrix:
  allow_failures:
  - go: tip
  include:
  - os: osx
    go: 1.8.1
deploy:
  provider: script
  script: make travis_beta
  on:
    branch: master
    go: 1.8.1
    condition: "`uname` == 'Linux'"
